export const contractAddress = "0xFf67d2D91A2a4c206679BE587cfEdBf7168BBeaf";
export const usdtAddress = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F";
export const pointAddress = "0xEf0E4Bc93AA3Cb770D20D7a8A09547448245c3e0";
export const contractOwner = "0x72C88D0c0aBF2488F4755Ba8188b8CcC226C8B0d";

export const contractABI = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_initialOwner",
        type: "address",
        internalType: "address",
      },
      {
        name: "_usdtAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "_supportiveWallet",
        type: "address",
        internalType: "address",
      },
      { name: "_feeWallet", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BUY_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DIVIDE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "LEVEL1_ENTRANCE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "LEVEL1_ENTRANCE_STAKE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "LOCK_DURATION",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_REWARD_BP",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MONTH_SECONDS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PRICE_DECIMALS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "REGISTRATION_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SELL_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TRANSFER_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "_pending",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint8", internalType: "uint8" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "addLiquidity",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "availableRewards",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "changeLevel1Entrance",
    inputs: [{ name: "newEntrance", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeLevel1EntranceStake",
    inputs: [{ name: "newEntrance", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimOpen",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimRewards",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeClaim",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeWallet",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getContractStage",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLocks",
    inputs: [{ name: "userAddr", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct Unity.Lock[]",
        components: [
          { name: "amount", type: "uint256", internalType: "uint256" },
          {
            name: "releaseTime",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUser",
    inputs: [{ name: "userAddr", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Unity.User",
        components: [
          {
            name: "userAddress",
            type: "address",
            internalType: "address",
          },
          { name: "username", type: "string", internalType: "string" },
          {
            name: "referrer",
            type: "address",
            internalType: "address",
          },
          {
            name: "referrerUsername",
            type: "string",
            internalType: "string",
          },
          {
            name: "firstDirect",
            type: "address",
            internalType: "address",
          },
          {
            name: "registrationTime",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "firstDirectLockAmount",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "directs", type: "uint256", internalType: "uint256" },
          {
            name: "directsAddresses",
            type: "address[]",
            internalType: "address[]",
          },
          {
            name: "unityPlan",
            type: "tuple",
            internalType: "struct Unity.PlanInfo",
            components: [
              { name: "isActive", type: "bool", internalType: "bool" },
              {
                name: "entryAmount",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "unlockedLevels",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "totalReward",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "credit",
                type: "uint256",
                internalType: "uint256",
              },
            ],
          },
          {
            name: "unirxPlan",
            type: "tuple",
            internalType: "struct Unity.PlanInfo",
            components: [
              { name: "isActive", type: "bool", internalType: "bool" },
              {
                name: "entryAmount",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "unlockedLevels",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "totalReward",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "credit",
                type: "uint256",
                internalType: "uint256",
              },
            ],
          },
          {
            name: "stakePlan",
            type: "tuple",
            internalType: "struct Unity.PlanInfo",
            components: [
              { name: "isActive", type: "bool", internalType: "bool" },
              {
                name: "entryAmount",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "unlockedLevels",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "totalReward",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "credit",
                type: "uint256",
                internalType: "uint256",
              },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserByUsername",
    inputs: [{ name: "username", type: "string", internalType: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Unity.User",
        components: [
          {
            name: "userAddress",
            type: "address",
            internalType: "address",
          },
          { name: "username", type: "string", internalType: "string" },
          {
            name: "referrer",
            type: "address",
            internalType: "address",
          },
          {
            name: "referrerUsername",
            type: "string",
            internalType: "string",
          },
          {
            name: "firstDirect",
            type: "address",
            internalType: "address",
          },
          {
            name: "registrationTime",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "firstDirectLockAmount",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "directs", type: "uint256", internalType: "uint256" },
          {
            name: "directsAddresses",
            type: "address[]",
            internalType: "address[]",
          },
          {
            name: "unityPlan",
            type: "tuple",
            internalType: "struct Unity.PlanInfo",
            components: [
              { name: "isActive", type: "bool", internalType: "bool" },
              {
                name: "entryAmount",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "unlockedLevels",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "totalReward",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "credit",
                type: "uint256",
                internalType: "uint256",
              },
            ],
          },
          {
            name: "unirxPlan",
            type: "tuple",
            internalType: "struct Unity.PlanInfo",
            components: [
              { name: "isActive", type: "bool", internalType: "bool" },
              {
                name: "entryAmount",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "unlockedLevels",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "totalReward",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "credit",
                type: "uint256",
                internalType: "uint256",
              },
            ],
          },
          {
            name: "stakePlan",
            type: "tuple",
            internalType: "struct Unity.PlanInfo",
            components: [
              { name: "isActive", type: "bool", internalType: "bool" },
              {
                name: "entryAmount",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "unlockedLevels",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "totalReward",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "credit",
                type: "uint256",
                internalType: "uint256",
              },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserStakes",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct Unity.Stake[]",
        components: [
          { name: "amount", type: "uint256", internalType: "uint256" },
          {
            name: "startTimestamp",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "lastClaim",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "rewardClaimed",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUsers",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lockedAmount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "locked", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "locks",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "releaseTime", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "openClaim",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "openSwap",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pauseStake",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "price",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "register",
    inputs: [
      { name: "_user", type: "address", internalType: "address" },
      { name: "_referrer", type: "address", internalType: "address" },
      {
        name: "registrationAmount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "username", type: "string", internalType: "string" },
      {
        name: "plan",
        type: "uint8",
        internalType: "enum Unity.PlanType",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rewardRateBP",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "stakeMore",
    inputs: [{ name: "usdtAmount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "stakerEarnings",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "startingDate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sumDownlineByPlan",
    inputs: [{ name: "_user", type: "address", internalType: "address" }],
    outputs: [
      { name: "unityValume", type: "uint256", internalType: "uint256" },
      { name: "unirxValume", type: "uint256", internalType: "uint256" },
      { name: "stakeValume", type: "uint256", internalType: "uint256" },
      {
        name: "unityMembers",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "unirxMembers",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "stakeMembers",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "members", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supportiveWallet",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "swap",
    inputs: [
      { name: "receiver", type: "address", internalType: "address" },
      { name: "isUnitytoUSDT", type: "bool", internalType: "bool" },
      { name: "inputAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "swapOpenForAll",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalAvailableRewards",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalUsers",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unirxToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract Unirx" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unlockedAmount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "unlocked", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unpauseStake",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "upgradePlan",
    inputs: [
      {
        name: "upgradeAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "planToUpgrade",
        type: "uint8",
        internalType: "enum Unity.PlanType",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "usdt",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usdtLiquidity",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userInfo",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "userAddress", type: "address", internalType: "address" },
      { name: "username", type: "string", internalType: "string" },
      { name: "referrer", type: "address", internalType: "address" },
      {
        name: "referrerUsername",
        type: "string",
        internalType: "string",
      },
      { name: "firstDirect", type: "address", internalType: "address" },
      {
        name: "registrationTime",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "firstDirectLockAmount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "directs", type: "uint256", internalType: "uint256" },
      {
        name: "unityPlan",
        type: "tuple",
        internalType: "struct Unity.PlanInfo",
        components: [
          { name: "isActive", type: "bool", internalType: "bool" },
          {
            name: "entryAmount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "unlockedLevels",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "totalReward",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "credit", type: "uint256", internalType: "uint256" },
        ],
      },
      {
        name: "unirxPlan",
        type: "tuple",
        internalType: "struct Unity.PlanInfo",
        components: [
          { name: "isActive", type: "bool", internalType: "bool" },
          {
            name: "entryAmount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "unlockedLevels",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "totalReward",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "credit", type: "uint256", internalType: "uint256" },
        ],
      },
      {
        name: "stakePlan",
        type: "tuple",
        internalType: "struct Unity.PlanInfo",
        components: [
          { name: "isActive", type: "bool", internalType: "bool" },
          {
            name: "entryAmount",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "unlockedLevels",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "totalReward",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "credit", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usernameToAddressMapping",
    inputs: [{ name: "", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawUnity",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "yieldSoFar",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AddLiquidity",
    inputs: [
      {
        name: "provider",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "spender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Register",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "referrer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "username",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "plan",
        type: "uint8",
        indexed: false,
        internalType: "enum Unity.PlanType",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RewardClaimed",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Swap",
    inputs: [
      {
        name: "isUnityToUSDT",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "caller",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "receiver",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "inputAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "outputAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SwapOpened",
    inputs: [
      {
        name: "time",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      {
        name: "from",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpgradePlan",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "plan",
        type: "uint8",
        indexed: false,
        internalType: "enum Unity.PlanType",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawUnity",
    inputs: [
      {
        name: "user",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "ERC20InsufficientAllowance",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "allowance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC20InsufficientBalance",
    inputs: [
      { name: "sender", type: "address", internalType: "address" },
      { name: "balance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC20InvalidApprover",
    inputs: [{ name: "approver", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidReceiver",
    inputs: [{ name: "receiver", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidSender",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidSpender",
    inputs: [{ name: "spender", type: "address", internalType: "address" }],
  },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
];
